# Generated by Django 4.2.5 on 2023-12-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fun_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
